# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/nmp/nmp.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nmp || ORIG_REF_NAME==nmp} -quiet] -quiet

# IP: bd/nmp/ip/nmp_processing_system7_0_0/nmp_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nmp_processing_system7_0_0 || ORIG_REF_NAME==nmp_processing_system7_0_0} -quiet] -quiet

# IP: bd/nmp/ip/nmp_xbar_0/nmp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nmp_xbar_0 || ORIG_REF_NAME==nmp_xbar_0} -quiet] -quiet

# IP: bd/nmp/ip/nmp_auto_pc_1/nmp_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nmp_auto_pc_1 || ORIG_REF_NAME==nmp_auto_pc_1} -quiet] -quiet

# IP: bd/nmp/ip/nmp_auto_pc_0/nmp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nmp_auto_pc_0 || ORIG_REF_NAME==nmp_auto_pc_0} -quiet] -quiet

# IP: bd/nmp/ip/nmp_axi_interconnect_0_0/nmp_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nmp_axi_interconnect_0_0 || ORIG_REF_NAME==nmp_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/nmp/ip/nmp_proc_sys_reset_0_0/nmp_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nmp_proc_sys_reset_0_0 || ORIG_REF_NAME==nmp_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/nmp/ip/nmp_nmp_axi4l_ip_0_1/nmp_nmp_axi4l_ip_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nmp_nmp_axi4l_ip_0_1 || ORIG_REF_NAME==nmp_nmp_axi4l_ip_0_1} -quiet] -quiet

# XDC: c:/Users/renan/Desktop/teste_vivado2/teste_vivado2.gen/sources_1/bd/nmp/nmp_ooc.xdc
