# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/renan/Desktop/teste_vivado2/teste_vivado2.srcs/sources_1/bd/nmp/ip/nmp_xbar_0/nmp_xbar_0.xci
# IP: The module: 'nmp_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/renan/Desktop/teste_vivado2/teste_vivado2.gen/sources_1/bd/nmp/ip/nmp_xbar_0/nmp_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'nmp_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/renan/Desktop/teste_vivado2/teste_vivado2.srcs/sources_1/bd/nmp/ip/nmp_xbar_0/nmp_xbar_0.xci
# IP: The module: 'nmp_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/renan/Desktop/teste_vivado2/teste_vivado2.gen/sources_1/bd/nmp/ip/nmp_xbar_0/nmp_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'nmp_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
